### ISSUE TITLE
Trouble using topExample()

### ISSUE THREAD

**Issue by daloonik** [jeremybrooks/knicker#4]
I'm getting an error when I try to use WordApi.topExample().
 For instance,
   Example ex = WordApi.topExample("cats",null,true);

Gets me the following error:
net.jeremybrooks.knicker.KnickerException: Error getting a response from the server.
	at net.jeremybrooks.knicker.Util.doGet(Util.java:144)
	at net.jeremybrooks.knicker.Util.doGet(Util.java:85)
	at net.jeremybrooks.knicker.WordApi.topExample(WordApi.java:431)
	at Wordniktest.main(Wordniktest.java:36)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://api.wordnik.com/v4/word.xml/cats/topExample?useCanonical=true
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at net.jeremybrooks.knicker.Util.doGet(Util.java:131)

**Comment by daloonik** [comment]
Actually this looks to be more of a problem with Wordnik.. http://api.wordnik.com/v4/word.json/cats/topExample?useCanonical=false&api_key=a2a73e7b926c924fad7001ca3111acd55af2ffabf50eb4ae5

**Comment by jeremybrooks** [comment]
Looks like this may have been a temporary server issue. I am able to use the topExample API right now:

`net.jeremybrooks.knicker.dto.Example: [ documentId=18094183 | exampleId=1185868246 | word=cat | rating=8939.131 | title=Famous Reviews | url=http://www.gutenberg.org/dirs/1/1/2/5/11251/11251-8.txt | text=In a subsequent passage, "I am as melancholy as a gibb'd cat" -- we are told that _cat_ is not the domestic animal of that name, but a contraction of _catin_, a woman of the town. | year=1899 | provider=net.jeremybrooks.knicker.dto.Provider: [ id= | name= ] ]`
