### ISSUE TITLE
Error getting a response from the server

### ISSUE THREAD

**Issue by daloonik** [jeremybrooks/knicker#6]
Knicker has suddenly started throwing KnickerExceptions and the error message is Error getting a response from the server.

     net.jeremybrooks.knicker.KnickerException: Error getting a response from the server.
     at net.jeremybrooks.knicker.Util.doGet(Util.java:144)
     at net.jeremybrooks.knicker.Util.doGet(Util.java:85)
     at net.jeremybrooks.knicker.WordsApi.randomWord(WordsApi.java:165)
     at net.jeremybrooks.knicker.WordsApi.randomWord(WordsApi.java:64)

And also this happens:

    Caused by: javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
    Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

But I'm not sure if this is related and I'm also not sure why this started occurring a few days ago.

**Comment by hkurra** [comment]
I am also facing the same issue on one of my Android App.
Earlier it was working fine

**Comment by hkurra** [comment]
![image](https://user-images.githubusercontent.com/6569316/60967473-5f11aa00-a338-11e9-9e80-8dfc43b9e17c.png)

**Comment by judeibe** [comment]
Looks like wordnik it no longer sends xml. Only json now. I think I may work on this part.

**Comment by HavocLee** [comment]
Did you guys have this issue resolved by any chance? I know its been a year, but I still have this problem. It says error receiving response from the server with error code 422 for x URL, which when I try to get on, it says no API Key found in request, even though I set an API key with System.setProperty();

**Comment by hkurra** [comment]
@HavocLee No, I was not able to work on this issue, I have started on this, but then I got busy somewhere else.
Moreover, I have disabled the features in my app dependent on this library due to other reasons
